### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by rmsilva1973** [shawaiz-khan/prioritx#17]
For devs to jump in I think we should define a basic development environment. That would include:

- [ ] Linting and Prettier configuration (VSCode)
- [ ] Editorconfig file (VSCode)
- [ ] Composer.yaml to spin MongoDB container (Backend)
- [ ] Basic scripts in package.json (Frontend)

**Comment by shawaiz-khan** [comment]
> For devs to jump in I think we should define a basic development environment. That would include:
> 
> * [ ]  Linting and Prettier configuration (VSCode)
> * [ ]  Editorconfig file (VSCode)
> * [ ]  Composer.yaml to spin MongoDB container (Backend)
> * [ ]  Basic scripts in package.json (Frontend)

Yeah that'll work. But I think setting up a DB is essential firstly, then we can move to these. What do you think?
